language: go

go:
  - "1.11"

os:
  - linux
  - windows

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libgles2-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
  chrome: stable

install:
  - mkdir /tmp/work
  - cd /tmp/work
  - go mod init example.com/m
  - go get github.com/hajimehoshi/ebiten@$TRAVIS_BRANCH
  - go get github.com/gopherjs/gopherjs
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get myitcv.io/cmd/gjbt; fi
  - # gopath-get for the current GopherJS and gjbt.
  - GO111MODULE=off go get -tags example github.com/hajimehoshi/ebiten/... 
  - GO111MODULE=off go get github.com/gopherjs/gopherjs
  - GO111MODULE=off go get github.com/gopherjs/gopherwasm/js
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir /tmp/google-chrome-bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s /usr/bin/google-chrome-stable /tmp/google-chrome-bin/google-chrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/tmp/google-chrome-bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -s https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip > /tmp/chromedriver_linux64.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip -d /tmp/chromedriver_linux64 /tmp/chromedriver_linux64.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/tmp/chromedriver_linux64:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y glfw3; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

script:
  - cd /tmp/work
  - go build -tags example -v github.com/hajimehoshi/ebiten/examples/...
  - go test -v github.com/hajimehoshi/ebiten/...
  - GOOS=linux gopherjs build --tags example -v github.com/hajimehoshi/ebiten/examples/blocks
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gjbt github.com/hajimehoshi/ebiten; fi # TODO: Test the subdirectories

# - test -z $(gofmt -s -l $GOPATH/src/github.com/hajimehoshi/ebiten)

notifications:
  email:
    recipients:
      - hajimehoshi@gmail.com
